#!/usr/bin/perl -w

#  Copyright 2012 ChuShin Koh<ChuShin.Koh@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.


use strict;
use Getopt::Long;

my $dovetail_file;
my $agp_file;

GetOptions("dovetail_file=s" => \$dovtail_file,
    "agp_file=s" => \$agp_file);

unless (defined $agp_file && $dovetail_file) {
print<<EOF;

This utility script convert a dovetail proprietary file in the format below:
Scnbf3h_1;HRSCAF=9  utg17_pilon  0  72207  +  0  72207
into NCBI AGP file.

Usage:
    util_dovetail2agp
        --dovetail_file    [-d]   input dovetail file
        --agp_file    [-o]   output agp file

EOF
exit 1;
}
